---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gke-rootlease-europe-west6-rootlease-prod-user
  namespace: gitops
spec:
  interval: 1m0s
  path: ./.weave-gitops/clusters/gke-rootlease-europe-west6-rootlease-prod/user
  prune: true
  sourceRef:
    kind: GitRepository
    name: wego-github-gitops-weaveworks

